# Generated by Django 2.2.3 on 2022-05-04 13:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '显卡型号',
                'verbose_name_plural': '显卡型号',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '主用人',
                'verbose_name_plural': '主用人',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='ip地址')),
                ('cpu', models.CharField(max_length=100, verbose_name='cpu型号')),
                ('gpu', models.CharField(max_length=100, verbose_name='gpu型号')),
                ('passwd', models.CharField(blank=True, max_length=100, verbose_name='密码')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(verbose_name='修改时间')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watermelon.Card', verbose_name='显卡型号')),
                ('user', models.ManyToManyField(blank=True, to='watermelon.User', verbose_name='主用人')),
            ],
        ),
    ]
